import { fromNumber } from "./chroma";
import { primeForm } from "./normal";
import { inversionalSymmetry, transpositionalSymmetry } from "./symmetry";
import { complement } from "./transform";
import type { IntervalVector, PcSet } from "./types";
import { intervalVector } from "./vector";

/** One entry of the set-class catalog, keyed by prime form. */
export interface CatalogEntry {
  /** Prime form of this set class. */
  readonly primeForm: PcSet;
  /** Stable key, equal to primeForm.join(","). */
  readonly key: string;
  /** Number of pitch classes. */
  readonly cardinality: number;
  /** Interval-class content. */
  readonly intervalVector: IntervalVector;
  /** Key of the complementary set class. */
  readonly complementKey: string;
  /** Key of the Z-related set class (same interval vector, different set class), or null. */
  readonly zPartnerKey: string | null;
  /** Count of transpositions mapping the set onto itself. */
  readonly transpositionalSymmetry: number;
  /** Count of inversions mapping the set onto itself. */
  readonly inversionalSymmetry: number;
}

const keyOf = (pf: readonly number[]): string => pf.join(",");

let cache: Map<string, CatalogEntry> | null = null;

/**
 * The complete set-class catalog for the 12-tone universe (224 classes), generated by
 * enumerating all 4096 pitch-class sets and folding them into set classes by prime form.
 * Z-relations are detected as distinct set classes that share an interval vector.
 * The result is computed once and memoized.
 */
export function catalog(): Map<string, CatalogEntry> {
  if (cache) return cache;

  const byKey = new Map<string, { primeForm: PcSet; intervalVector: IntervalVector }>();
  for (let num = 0; num <= 4095; num++) {
    const pf = primeForm(fromNumber(num));
    const key = keyOf(pf);
    if (!byKey.has(key)) byKey.set(key, { primeForm: pf, intervalVector: intervalVector(pf) });
  }

  // Group set classes by cardinality and interval vector to find Z-relations.
  const ivGroups = new Map<string, string[]>();
  for (const [key, { primeForm: pf, intervalVector: iv }] of byKey) {
    const group = `${pf.length}:${iv.join("")}`;
    const arr = ivGroups.get(group);
    if (arr) arr.push(key);
    else ivGroups.set(group, [key]);
  }

  const out = new Map<string, CatalogEntry>();
  for (const [key, { primeForm: pf, intervalVector: iv }] of byKey) {
    const group = ivGroups.get(`${pf.length}:${iv.join("")}`) as string[];
    const zPartnerKey = group.length === 2 ? (group.find((k) => k !== key) ?? null) : null;
    out.set(key, {
      primeForm: pf,
      key,
      cardinality: pf.length,
      intervalVector: iv,
      complementKey: keyOf(primeForm(complement(pf))),
      zPartnerKey,
      transpositionalSymmetry: transpositionalSymmetry(pf),
      inversionalSymmetry: inversionalSymmetry(pf),
    });
  }

  cache = out;
  return out;
}

/** Look up the catalog entry for a set class by the prime form of the given pitch-class set. */
export function catalogEntry(pcs: readonly number[]): CatalogEntry {
  const entry = catalog().get(keyOf(primeForm(pcs)));
  if (!entry) {
    // Unreachable: every pitch-class set has a prime form present in the catalog.
    throw new Error(`set class not found in catalog for ${JSON.stringify([...pcs])}`);
  }
  return entry;
}
